# Generated by Django 2.1.4 on 2018-12-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_code', models.IntegerField(help_text='4 digit unique Syllabus Code')),
                ('syllabus_title', models.CharField(help_text='Name of the Subject', max_length=100)),
                ('board', models.IntegerField(choices=[(1, 'Cambridge'), (2, 'Edexcel')], default=1)),
                ('level', models.IntegerField(choices=[(1, 'O Levels'), (2, 'IGCSE'), (3, 'A Levels')], default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('syllabus_code',)},
        ),
    ]
