# Generated by Django 2.1.4 on 2019-01-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='author',
            new_name='account',
        ),
    ]
