# Generated by Django 2.1.4 on 2018-12-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0002_auto_20181228_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='Question Number')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('solution', models.CharField(help_text='Can use Latex code in solution', max_length=100)),
                ('file_link', models.CharField(help_text='link to animation/video', max_length=100)),
                ('difficulty', models.FloatField(help_text='for heuristics')),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='season',
            field=models.CharField(choices=[('s', 'summer'), ('m', 'mid session'), ('w', 'winter')], default='s', max_length=2),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(help_text='Last two digits of the year of the exam'),
        ),
        migrations.AddField(
            model_name='solution',
            name='paper_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='question_model.Paper'),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('paper_reference', 'question_number')},
        ),
    ]
