# Generated by Django 2.1.4 on 2018-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0003_auto_20181228_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.EmailField(help_text='Enter your email', max_length=254, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Full name of customer', max_length=100)),
                ('avatar', models.CharField(help_text='Choose an avatar', max_length=100)),
                ('phone', models.CharField(help_text='Enter your phone number using the format +880**********', max_length=14)),
                ('school', models.CharField(help_text='Enter the name your school', max_length=50)),
                ('Class', models.IntegerField(choices=[(9, 'Nine'), (10, 'O Levels/IGCSE'), (11, 'AS Level'), (12, 'A Levels')], help_text='Which class are you currently studing?')),
                ('date_of_birth', models.DateField(help_text='Enter your date of birth')),
                ('credit', models.IntegerField(default=100)),
                ('social_media_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='file_link',
            field=models.CharField(blank=True, help_text='link to animation/video (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='syllabus_code',
            field=models.IntegerField(help_text='4 digit unique Syllabus Code', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
    ]
