# Generated by Django 2.1.4 on 2018-12-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0004_auto_20181228_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(help_text='Chapter number according to syllabus')),
                ('chapter_name', models.CharField(help_text='Chapter name (accoridng to syllabus)', max_length=100)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='question_model.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='chapter_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='question_model.Chapter'),
        ),
    ]
