# Generated by Django 2.1.4 on 2018-12-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0005_auto_20181228_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='question_model.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='question_model.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_number')},
        ),
        migrations.AddField(
            model_name='license',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_ID', to='question_model.Paper'),
        ),
    ]
