# Generated by Django 2.1.4 on 2018-12-28 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0006_auto_20181228_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='paper',
            new_name='paper_ID',
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Class',
            field=models.IntegerField(choices=[(9, '9 (O Levels/IGCSE)'), (10, '10 (O Levels/IGCSE)'), (11, '11 (AS Level)'), (12, '12 (A Levels)')], help_text='Which class are you currently studying?'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('account_ID', 'paper_ID')},
        ),
    ]
