# Generated by Django 2.1.4 on 2018-12-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0007_auto_20181228_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.FileField(help_text='Full name of customer', upload_to='avatars/'),
        ),
    ]
