# Generated by Django 2.1.4 on 2018-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0008_auto_20181228_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(help_text='Enter your password', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.FileField(help_text='Choose an avatar', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(help_text='Enter your full name', max_length=100),
        ),
    ]
