# Generated by Django 2.1.4 on 2018-12-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0009_auto_20181228_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, default=1000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='hello', help_text='Enter your password', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='syllabus_code',
            field=models.IntegerField(help_text='4 digit unique Syllabus Code', null=True),
        ),
    ]
