# Generated by Django 2.1.4 on 2018-12-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0010_auto_20181228_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='syllabus_code',
            field=models.IntegerField(default=1000, help_text='4 digit unique Syllabus Code', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
