# Generated by Django 2.1.4 on 2018-12-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0012_auto_20181228_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='question_model.Subject'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='file_link',
            field=models.FileField(blank=True, help_text='link to animation/video (optional)', upload_to='solutions/'),
        ),
    ]
