# Generated by Django 2.1.4 on 2018-12-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0013_auto_20181228_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='number_of_questions',
            field=models.IntegerField(default=40, help_text='Total number of questions'),
        ),
    ]
