# Generated by Django 2.1.4 on 2018-12-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0014_auto_20181228_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Class',
            field=models.IntegerField(choices=[(9, '9 (O Level/IGCSE)'), (10, '10 (O Level/IGCSE)'), (11, '11 (AS Level)'), (12, '12 (A Level)')], help_text='Which class are you currently studying?'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='paper_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to='question_model.Paper'),
        ),
    ]
