# Generated by Django 2.1.4 on 2018-12-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0015_auto_20181228_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='paper_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to='question_model.Paper'),
        ),
    ]
