# Generated by Django 2.1.4 on 2019-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0017_auto_20181229_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Class',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.IntegerField(choices=[(1, 'O Levels'), (2, 'IGCSE'), (11, 'AS Level'), (12, 'A Level')], default=0, help_text='Which level are you currently in?'),
        ),
    ]
