# Generated by Django 2.1.4 on 2019-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_model', '0019_auto_20190111_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.IntegerField(choices=[(1, 'O Levels'), (2, 'IGCSE'), (3, 'A Levels')], default=0, help_text='Which level are you currently in?'),
        ),
    ]
